"functions":
- "name": "jp_parse"
  "file": "./ast.c"
  "params":
  - "name": "expr"
    "type": "const char*"
  "return_type": "void"
  "signature": "jp_parse(const char *expr)"
- "name": "jp_get_token"
  "file": "./lexer.c"
  "params":
  - "name": "s"
    "type": "struct jp_state*"
  - "name": "input"
    "type": "const char*"
  - "name": "mlen"
    "type": "int*"
  "return_type": "void"
  "signature": "jp_get_token(struct jp_state *s, const char *input, int *mlen)"
- "name": "buildshifts"
  "file": "./contrib/lemon.c"
  "params":
  - "name": "lemon"
    "type": "struct*"
  - "name": "state"
    "type": "struct*"
  "return_type": "PRIVATE void"
  "signature": "PRIVATE void buildshifts(struct lemon *, struct state *); /* Forwd ref */ PRIVATE struct state *getstate(struct lemon *lemp)"
- "name": "buildshifts"
  "file": "./contrib/lemon.c"
  "params":
  - "name": "lemp"
    "type": "struct lemon*"
  - "name": "stp"
    "type": "struct state*"
  "return_type": "PRIVATE void"
  "signature": "PRIVATE void buildshifts(struct lemon *lemp, struct state *stp)"
- "name": "Parse"
  "file": "./contrib/lemon.c"
  "params":
  - "name": "gp"
    "type": "struct lemon*"
  "return_type": "void"
  "signature": "void Parse(struct lemon *gp)"